nomadanimals2=subset(animals, animals$SOCIOECONOMIC=="NOMADIC")
hist(nomadanimals2$carbon, xlab="δ13C‰", main="Carbon data for animals in Nomadic Settings", col="lavender")
urbananimals=subset(animals, animals$SOCIOECONOMIC=="URBAN")
hist(urbananimals$carbon, xlab="δ13C‰", main="Carbon data for animals in Urban Settings", col="lightblue")
shapiro.test(urbananimals$carbon)
wilcox.test(x=nomadanimals2$carbon, y=urbananimals$carbon)
hist(nomadanimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Nomadic Settings", col="turquoise4")
hist(urbananimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Urban Settings", col="orange")
shapiro.test(urbananimals$nitrogen)
wilcox.test(x=nomadanimals2$nitrogen, y=urbananimals$nitrogen)
hist(nomadanimals2$oxygen, xlab="δ18O‰", main="Oxygen data for animals in Nomadic Settings", col="lightpink")
shapiro.test(nomadanimals2$oxygen)
hist(urbananimals$oxygen, xlab="δ18O‰", main="Oxygen data for animals in Urban Settings", col="yellowgreen")
shapiro.test(urbananimals$oxygen)
wilcox.test(x=nomadanimals2$oxygen, y=urbananimals$oxygen)
nomadhuman=subset(human, human$SOCIOECONOMIC=="NOMADIC")
hist(nomadhuman$carbon, xlab="δ13C‰", main="Carbon data for humans in Nomadic Settings", col="tomato3")
shapiro.test(nomadhuman$carbon)
urbanhuman=subset(human, human$SOCIOECONOMIC=="URBAN")
hist(urbanhuman$carbon, xlab="δ13C‰", main="Carbon data for humans in Urban Settings", col="steelblue")
shapiro.test(urbanhuman$carbon)
wilcox.test(x=urbanhuman$carbon, y=nomadhuman$carbon)
hist(nomadhuman$nitrogen, xlab="δ15N‰", main="Nitrogen data for humans in Nomadic Settings", col="salmon")
shapiro.test(nomadhuman$nitrogen)
hist(urbanhuman$nitrogen, xlab="δ15N‰", main="Nitrogen data for humans in Urban Settings", col="navajowhite")
shapiro.test(urbanhuman$nitrogen)
t.test(x=urbanhuman$nitrogen, y=nomadhuman$nitrogen)
hist(nomadhuman2$oxygen, xlab="δ18O‰", main="Oxygen data for humans in nomadic Settings", col="salmon")
shapiro.test(nomadhuman2$oxygen)
mean(nomadhuman2$oxygen, na.rm=TRUE)
t.test(x=nomadhuman2$oxygen, -6.7, var.equal=TRUE)
Aanimals=subset(animals, animals$ENVIRONMENT=="A - SEMI-ARID STEPPE")
hist(Aanimals$carbon, xlab="δ13C‰", main="Carbon data for animals in Semi Arid Steppe", col="olivedrab4")
shapiro.test(Aanimals$carbon)
Banimals=subset(animals, animals$ENVIRONMENT=="B - FOREST STEPPE")
hist(Banimals$carbon, xlab="δ13C‰", main="Carbon data for animals in Forest Steppe", col="saddlebrown")
shapiro.test(Banimals$carbon)
Canimals=subset(animals, animals$ENVIRONMENT=="C - WEST STEPPE")
hist(Canimals$carbon, xlab="δ13C‰", main="Carbon data for animals in West Steppe", col="palevioletred1")
shapiro.test(Canimals$carbon)
Danimals=subset(animals, animals$ENVIRONMENT=="D - MOUNTAIN/FOREST STEPPE")
hist(Danimals$carbon, xlab="δ13C‰", main="Carbon data for animals in Mountain/Forest Steppe", col="peachpuff4")
shapiro.test(Danimals$carbon)
Eanimals=subset(animals, animals$ENVIRONMENT=="E - ARID/MOUNTAIN STEPPE")
hist(Eanimals$carbon, xlab="δ13C‰", main="Carbon data for animals in Arid/Mountain Steppe", col="magenta4")
shapiro.test(Eanimals$carbon)
Fanimals=subset(animals, animals$ENVIRONMENT=="F - DESERT OASES")
hist(Fanimals$carbon, xlab="δ13C‰", main="Carbon data for animals in Desert Oases", col="dodgerblue")
shapiro.test(Fanimals$carbon)
Ganimals=subset(animals, animals$ENVIRONMENT=="G - ARID DESERT")
hist(Ganimals$carbon, xlab="δ13C‰", main="Carbon data for animals in Arid Desert", col="indianred3")
kruskal.test(animals$carbon ~ animals$ENVIRONMENT, data=animals) 
install.packages("rstatix")
dunn_test(animals, carbon ~ ENVIRONMENT)
CanimalsEnvironment =dunn_test(animals, carbon ~ ENVIRONMENT)
summary(CanimalsEnvironment)
hist(Aanimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Semi - Arid Steppe", col="firebrick4")
shapiro.test(Aanimals$nitrogen)
hist(Banimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Forest Steppe", col="forestgreen")
shapiro.test(Banimals$nitrogen)
hist(Canimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in West Steppe", col="rosybrown1")
shapiro.test(Canimals$nitrogen)
hist(Danimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Mountain/Forest Steppe", col="wheat4")
shapiro.test(Danimals$nitrogen)
hist(Eanimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Arid/Mountain Steppe", col="tan2")
shapiro.test(Eanimals$nitrogen)
hist(Fanimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Desert Oases", col="mediumpurple")
shapiro.test(Fanimals$nitrogen)
hist(Ganimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for animals in Arid Desert", col="lemonchiffon2")
shapiro.test(Ganimals$nitrogen)
kruskal.test(animals$nitrogen ~ animals$ENVIRONMENT, data=animals)
Nanimalsenvironment = dunn_test(animals, nitrogen ~ ENVIRONMENT)
summary(Nanimalsenvironment)
hist(Aanimals$oxygen, xlab="δ18O‰", main="Oxygen data for animals in Semi-Arid Steppe", col="slateblue2")
shapiro.test(Aanimals$oxygen)
hist(Danimals$oxygen, xlab="δ18O‰", main="Oxygen data for animals in Mountain/Forest Steppe", col="skyblue")
shapiro.test(Danimals$oxygen)
hist(Eanimals$oxygen, xlab="δ18O‰", main="Oxygen data for animals in Arid/Mountain Steppe", col="mediumaquamarine")
shapiro.test(Eanimals$oxygen)
hist(Ganimals$oxygen, xlab="δ18O‰", main="Oxygen data for animals in Arid Desert", col="seagreen")
shapiro.test(Ganimals$oxygen)
oneway.test(animals$oxygen ~ animals$ENVIRONMENT, data=animals)
result=aov(animals$oxygen ~ animals$ENVIRONMENT, data=animals)
TukeyHSD(result)
DTN=dunn_test(animals, nitrogen ~ ENVIRONMENT)
View(DTN)
DTC=dunn_test(animals, carbon ~ ENVIRONMENT)
View(DTC)
plot(result)
T=TukeyHSD(result)
plot(T, las=1)
par(mar=c(5,27,4,1))
plot(T, las=1)
Ahuman=subset(human, human$ENVIRONMENT=="A - SEMI-ARID STEPPE")
par(mar=c(4,4,4,4))
hist(Ahuman$carbon, xlab="δ13C‰", main="Carbon data for Humans in Semi-Arid Steppe", col="springgreen4")
shapiro.test(Ahuman$carbon)
Bhuman=subset(human, human$ENVIRONMENT=="B - FOREST STEPPE")
hist(Bhuman$carbon, xlab="δ13C‰", main="Carbon data for Humans in Forest Steppe", col="slategrey")
shapiro.test(Bhuman$carbon)
Chuman=subset(human, human$ENVIRONMENT=="C - WEST STEPPE")
hist(Chuman$carbon, xlab="δ13C‰", main="Carbon data for Humans in West Steppe", col="sienna3")
shapiro.test(Chuman$carbon)
Dhuman=subset(human, human$ENVIRONMENT=="D - MOUNTAIN/FOREST STEPPE")
hist(Dhuman$carbon, xlab="δ13C‰", main="Carbon data for Humans in Mountain/Forest Steppe", col="plum3")
shapiro.test(Dhuman$carbon)
Ehuman=subset(human, human$ENVIRONMENT=="E - ARID/MOUNTAIN STEPPE")
hist(Ehuman$carbon, xlab="δ13C‰", main="Carbon data for Humans in Arid/Mountain Steppe", col="hotpink2")
shapiro.test(Ehuman$carbon)
Fhuman=subset(human, human$ENVIRONMENT=="F - DESERT OASES")
hist(Fhuman$carbon, xlab="δ13C‰", main="Carbon data for Humans in Desert Oases", col="paleturquoise2")
shapiro.test(Fhuman$carbon)
Ghuman=subset(human, human$ENVIRONMENT=="G - ARID DESERT")
hist(Ghuman$carbon, xlab="δ13C‰", main="Carbon data for Humans in Arid Desert", col="lavenderblush3")
shapiro.test(Ghuman$carbon)
kruskal.test(human$carbon~human$ENVIRONMENT, data=human)
DTCH=dunn_test(human, carbon ~ ENVIRONMENT)
summary(DTCH)
View(DTCH)
hist(Ahuman$nitrogen, xlab="δ15N‰", main="Nitrogen data for Humans in Semi-Arid Steppe", col="violet")
shapiro.test(Ahuman$nitrogen)
hist(Bhuman$nitrogen, xlab="δ15N‰", main="Nitrogen data for Humans in Forest Steppe", col="orangered3")
shapiro.test(Bhuman$nitrogen)
hist(Chuman$nitrogen, xlab="δ15N‰", main="Nitrogen data for Humans in WEST Steppe", col="lightsteelblue2")
shapiro.test(Chuman$nitrogen)
hist(Dhuman$nitrogen, xlab="δ15N‰", main="Nitrogen data for Humans in Mountain/Forest Steppe", col="olivedrab")
shapiro.test(Dhuman$nitrogen)
hist(Ehuman$nitrogen, xlab="δ15N‰", main="Nitrogen data for Humans in Arid/Mountain Steppe", col="mediumorchid")
shapiro.test(Ehuman$nitrogen)
hist(Fhuman$nitrogen, xlab="δ15N‰", main="Nitrogen data for Humans in DESERT OASES", col="royalblue4")
shapiro.test(Fhuman$nitrogen)
hist(Ghuman$nitrogen, xlab="δ15N‰", main="Nitrogen data for Humans in Arid Desert", col="khaki1")
shapiro.test(Ghuman$nitrogen)
kruskal.test(human$nitrogen~human$ENVIRONMENT, data=human)
DTNH=dunn_test(human, nitrogen ~ ENVIRONMENT)
summary(DTNH)
View(DTNH)
hist(Bhuman$oxygen, xlab="δ18O‰", main="Oxygen data for Humans in Forest Steppe", col="thistle2")
shapiro.test(Bhuman$oxygen)
Bronzeanimals=subset(animals, animals$CHRONOLOGY=="BRONZE AGE")
hist(Bronzeanimals$carbon, xlab="δ13C‰", main="Carbon data for Animals in Bronze Age", col="powderblue")
shapiro.test(Bronzeanimals$carbon)
Ironanimals=subset(animals, animals$CHRONOLOGY=="IRON AGE")
hist(Ironanimals$carbon, xlab="δ13C‰", main="Carbon data for Animals in Iron Age", col="ivory3")
shapiro.test(Ironanimals$carbon)
LANTanimals=subset(animals, animals$CHRONOLOGY=="LATE ANTIQUITY")
hist(LANTanimals$carbon, xlab="δ13C‰", main="Carbon data for Animals in Late Antiquity", col="pink2")
shapiro.test(LANTanimals$carbon)
Medievalanimals=subset(animals, animals$CHRONOLOGY=="MEDIEVAL")
hist(Medievalanimals$carbon, xlab="δ13C‰", main="Carbon data for Animals in Medieval", col="lemonchiffon1")
shapiro.test(Medievalanimals$carbon)
kruskal.test(animals$carbon~animals$CHRONOLOGY, data=animals)
DTCCA=dunn_test(animals, carbon ~ CHRONOLOGY)
summary(DTCCA)
hist(Bronzeanimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for Animals in the Bronze Age", col="sandybrown")
shapiro.test(Bronzeanimals$nitrogen)
hist(Ironanimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for Animals in the Iron Age", col="burlywood3")
shapiro.test(Ironanimals$nitrogen)
hist(LANTanimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for Animals in Late Antiquity", col="mistyrose3")
shapiro.test(LANTanimals$nitrogen)
hist(Medievalanimals$nitrogen, xlab="δ15N‰", main="Nitrogen data for Animals in the Medieval Period", col="lawngreen")
shapiro.test(Medievalanimals$nitrogen)
kruskal.test(animals$nitrogen~animals$CHRONOLOGY, data=animals)
DTCNA=dunn_test(animals, nitrogen ~ CHRONOLOGY)
summary(DTCNA)
View(DTCNA)
hist(Bronzeanimals$oxygen, xlab="δ18O‰", main="Oxygen data for Animals in Bronze Age", col="chartreuse4")
shapiro.test(Bronzeanimals$oxygen)
hist(Ironanimals$oxygen, xlab="δ18O‰", main="Oxygen data for Animals in Iron Age", col="chocolate2")
shapiro.test(Ironanimals$oxygen)
hist(Medievalanimals$oxygen, xlab="δ18O‰", main="Oxygen data for Animals in the Medieval Period", col="chocolate4")
shapiro.test(Medievalanimals$oxygen)
kruskal.test(animals$oxygen~animals$CHRONOLOGY, data=animals)
DTCOA=dunn_test(animals, oxygen ~ CHRONOLOGY)
summary(DTCOA)
View(DTCOA)
Bronzehuman=subset(human, human$CHRONOLOGY=="BRONZE AGE")

shapiro.test(Bronzehuman$carbon)
Ironhuman=subset(human, human$CHRONOLOGY=="IRON AGE")
hist(Ironhuman$carbon, xlab="δ13C‰", main="Carbon data for Humans in the Iron Age", col="bisque2")
shapiro.test(Ironhuman$carbon)
LANThuman=subset(human, human$CHRONOLOGY=="LATE ANTIQUITY")
hist(LANThuman$carbon, xlab="δ13C‰", main="Carbon data for Humans in Late Antiquity", col="blanchedalmond")
shapiro.test(LANThuman$carbon)
Medievalhuman=subset(human, human$CHRONOLOGY=="MEDIEVAL")
hist(Medievalhuman$carbon, xlab="δ13C‰", main="Carbon data for Humans in the Medieval Period", col="blue4")
shapiro.test(Medievalhuman$carbon)
kruskal.test(human$carbon~human$CHRONOLOGY, data=human)
DTCCH=dunn_test(human, carbon ~ CHRONOLOGY)
summary(DTCCH)
View(DTCCH)
hist(Bronzehuman$nitrogen, xlab="δ15N‰", main="Nitrogen data for Humans in the Bronze Age", col="brown2")
shapiro.test(Bronzehuman$nitrogen)
hist(Ironhuman$nitrogen, xlab="δ15N‰", main="Nitrogen data for Humans in the Iron Age", col="brown4")
shapiro.test(Ironhuman$nitrogen)
hist(LANThuman$nitrogen, xlab="δ15N‰", main="Nitrogen data for Humans in Late Antiquity", col="cadetblue")
shapiro.test(LANThuman$nitrogen)
hist(Medievalhuman$nitrogen, xlab="δ15N‰", main="Nitrogen data for Humans in the Medieval period", col="cadetblue2")
shapiro.test(Medievalhuman$nitrogen)
oneway.test(human$nitrogen ~ human$CHRONOLOGY, data=human)
result=aov(human$nitrogen ~ human$CHRONOLOGY, data=human)
TukeyHSD(result)
CHN=TukeyHSD(result)
par(mar=c(5,16,4,1))
plot(CHN, las=1)
hist(Bronzehuman$oxygen, xlab="δ18O‰", main="Oxygen data for Humans in the Bronze Age", col="coral2")
shapiro.test(Bronzehuman$oxygen)